; [local]
; localhost ansible_connection=local

[test]
test-node ansible_host=localhost ansible_port=2222 ansible_user=test-admin

[uat]
uat-node ansible_host=localhost ansible_port=2223 ansible_user=uat-admin

[prd]
prd-node ansible_host=localhost ansible_port=2224 ansible_user=prd-admin

[docker_lab:children]
test
uat
prd

[docker_lab:vars]
ansible_ssh_pass=password
ansible_become_pass=password
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3